import React from 'react'
import StyledContent from './style'

const Content = () => (
  <StyledContent>
    {`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi posuere a turpis eget vulputate. Etiam imperdiet nulla at vestibulum accumsan. Integer viverra id arcu eget varius. Suspendisse accumsan metus et magna volutpat, eu tincidunt augue lacinia. Fusce vel nisl ut nibh ultrices facilisis eu quis odio. Aliquam nec nunc diam. Sed hendrerit quis ipsum et sollicitudin. Quisque consequat, massa ut scelerisque facilisis, diam metus interdum est, id suscipit neque sem ut nunc. Nam sed porttitor tellus, nec facilisis velit. Suspendisse volutpat, leo at eleifend rhoncus, sem sapien sollicitudin felis, sed lobortis nunc mi quis eros.

Integer eget sem vel mauris hendrerit posuere in non mi. Aliquam tincidunt metus nunc, ac mattis massa convallis id. Maecenas in ultrices sapien, vitae facilisis lectus. Maecenas imperdiet augue id nibh interdum pretium. Quisque iaculis venenatis mauris, at vehicula nisi tempor tempus. Pellentesque purus tortor, commodo porta cursus a, interdum non diam. Nulla non dignissim nibh. Sed nec lacus lorem. Aenean eget porttitor erat. Phasellus sodales est eget maximus posuere. Donec pellentesque blandit est tristique malesuada. In condimentum nisi ut orci vulputate, at suscipit odio mollis. Integer vel tincidunt ipsum, id accumsan ante.

Aenean sit amet lobortis turpis. Vestibulum sit amet turpis nunc. Mauris enim risus, eleifend a mi sed, faucibus pellentesque enim. Etiam sit amet lectus eget purus finibus euismod. Nullam dictum diam sit amet felis volutpat ornare. Vestibulum gravida sapien at feugiat sollicitudin. Praesent neque nisi, accumsan id mi vel, ullamcorper consectetur tortor. Ut eget auctor nisi, quis auctor dui.

Quisque dui est, eleifend id rhoncus non, maximus sed justo. Aenean tincidunt, urna et congue vehicula, diam lacus luctus quam, a malesuada nisl urna sit amet ante. Duis venenatis pharetra magna, sit amet imperdiet eros placerat at. Morbi nec odio vel justo mattis faucibus ac a lorem. Ut consectetur, nisl in ornare feugiat, ante metus fringilla leo, at accumsan dui diam malesuada lacus. Duis justo odio, gravida in feugiat sed, pretium ac massa. Aliquam venenatis lacinia nisl sit amet euismod. Donec posuere accumsan consequat. Suspendisse interdum leo vitae lorem tincidunt, nec consectetur augue sagittis. Ut sodales ante ante, fringilla tempus mauris placerat dapibus. Aenean non leo ac velit laoreet cursus.

Fusce vehicula dapibus sodales. In feugiat imperdiet efficitur. Donec ut iaculis lorem. Ut condimentum placerat nunc at condimentum. In viverra nisi at odio pretium tristique. Maecenas euismod est purus, luctus commodo dui egestas vitae. Nulla facilisis, arcu id cursus mattis, lorem ipsum maximus mauris, eu accumsan est justo sit amet nisl. Maecenas efficitur pharetra luctus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi posuere a turpis eget vulputate. Etiam imperdiet nulla at vestibulum accumsan. Integer viverra id arcu eget varius. Suspendisse accumsan metus et magna volutpat, eu tincidunt augue lacinia. Fusce vel nisl ut nibh ultrices facilisis eu quis odio. Aliquam nec nunc diam. Sed hendrerit quis ipsum et sollicitudin. Quisque consequat, massa ut scelerisque facilisis, diam metus interdum est, id suscipit neque sem ut nunc. Nam sed porttitor tellus, nec facilisis velit. Suspendisse volutpat, leo at eleifend rhoncus, sem sapien sollicitudin felis, sed lobortis nunc mi quis eros.

Integer eget sem vel mauris hendrerit posuere in non mi. Aliquam tincidunt metus nunc, ac mattis massa convallis id. Maecenas in ultrices sapien, vitae facilisis lectus. Maecenas imperdiet augue id nibh interdum pretium. Quisque iaculis venenatis mauris, at vehicula nisi tempor tempus. Pellentesque purus tortor, commodo porta cursus a, interdum non diam. Nulla non dignissim nibh. Sed nec lacus lorem. Aenean eget porttitor erat. Phasellus sodales est eget maximus posuere. Donec pellentesque blandit est tristique malesuada. In condimentum nisi ut orci vulputate, at suscipit odio mollis. Integer vel tincidunt ipsum, id accumsan ante.

Aenean sit amet lobortis turpis. Vestibulum sit amet turpis nunc. Mauris enim risus, eleifend a mi sed, faucibus pellentesque enim. Etiam sit amet lectus eget purus finibus euismod. Nullam dictum diam sit amet felis volutpat ornare. Vestibulum gravida sapien at feugiat sollicitudin. Praesent neque nisi, accumsan id mi vel, ullamcorper consectetur tortor. Ut eget auctor nisi, quis auctor dui.

Quisque dui est, eleifend id rhoncus non, maximus sed justo. Aenean tincidunt, urna et congue vehicula, diam lacus luctus quam, a malesuada nisl urna sit amet ante. Duis venenatis pharetra magna, sit amet imperdiet eros placerat at. Morbi nec odio vel justo mattis faucibus ac a lorem. Ut consectetur, nisl in ornare feugiat, ante metus fringilla leo, at accumsan dui diam malesuada lacus. Duis justo odio, gravida in feugiat sed, pretium ac massa. Aliquam venenatis lacinia nisl sit amet euismod. Donec posuere accumsan consequat. Suspendisse interdum leo vitae lorem tincidunt, nec consectetur augue sagittis. Ut sodales ante ante, fringilla tempus mauris placerat dapibus. Aenean non leo ac velit laoreet cursus.

Fusce vehicula dapibus sodales. In feugiat imperdiet efficitur. Donec ut iaculis lorem. Ut condimentum placerat nunc at condimentum. In viverra nisi at odio pretium tristique. Maecenas euismod est purus, luctus commodo dui egestas vitae. Nulla facilisis, arcu id cursus mattis, lorem ipsum maximus mauris, eu accumsan est justo sit amet nisl. Maecenas efficitur pharetra luctus.Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi posuere a turpis eget vulputate. Etiam imperdiet nulla at vestibulum accumsan. Integer viverra id arcu eget varius. Suspendisse accumsan metus et magna volutpat, eu tincidunt augue lacinia. Fusce vel nisl ut nibh ultrices facilisis eu quis odio. Aliquam nec nunc diam. Sed hendrerit quis ipsum et sollicitudin. Quisque consequat, massa ut scelerisque facilisis, diam metus interdum est, id suscipit neque sem ut nunc. Nam sed porttitor tellus, nec facilisis velit. Suspendisse volutpat, leo at eleifend rhoncus, sem sapien sollicitudin felis, sed lobortis nunc mi quis eros.

Integer eget sem vel mauris hendrerit posuere in non mi. Aliquam tincidunt metus nunc, ac mattis massa convallis id. Maecenas in ultrices sapien, vitae facilisis lectus. Maecenas imperdiet augue id nibh interdum pretium. Quisque iaculis venenatis mauris, at vehicula nisi tempor tempus. Pellentesque purus tortor, commodo porta cursus a, interdum non diam. Nulla non dignissim nibh. Sed nec lacus lorem. Aenean eget porttitor erat. Phasellus sodales est eget maximus posuere. Donec pellentesque blandit est tristique malesuada. In condimentum nisi ut orci vulputate, at suscipit odio mollis. Integer vel tincidunt ipsum, id accumsan ante.

Aenean sit amet lobortis turpis. Vestibulum sit amet turpis nunc. Mauris enim risus, eleifend a mi sed, faucibus pellentesque enim. Etiam sit amet lectus eget purus finibus euismod. Nullam dictum diam sit amet felis volutpat ornare. Vestibulum gravida sapien at feugiat sollicitudin. Praesent neque nisi, accumsan id mi vel, ullamcorper consectetur tortor. Ut eget auctor nisi, quis auctor dui.

Quisque dui est, eleifend id rhoncus non, maximus sed justo. Aenean tincidunt, urna et congue vehicula, diam lacus luctus quam, a malesuada nisl urna sit amet ante. Duis venenatis pharetra magna, sit amet imperdiet eros placerat at. Morbi nec odio vel justo mattis faucibus ac a lorem. Ut consectetur, nisl in ornare feugiat, ante metus fringilla leo, at accumsan dui diam malesuada lacus. Duis justo odio, gravida in feugiat sed, pretium ac massa. Aliquam venenatis lacinia nisl sit amet euismod. Donec posuere accumsan consequat. Suspendisse interdum leo vitae lorem tincidunt, nec consectetur augue sagittis. Ut sodales ante ante, fringilla tempus mauris placerat dapibus. Aenean non leo ac velit laoreet cursus.

Fusce vehicula dapibus sodales. In feugiat imperdiet efficitur. Donec ut iaculis lorem. Ut condimentum placerat nunc at condimentum. In viverra nisi at odio pretium tristique. Maecenas euismod est purus, luctus commodo dui egestas vitae. Nulla facilisis, arcu id cursus mattis, lorem ipsum maximus mauris, eu accumsan est justo sit amet nisl. Maecenas efficitur pharetra luctus.`}
  </StyledContent>
)

export default Content
